/* సంపూర్ణ మహాభారతము — offline.
   The whole site is small and finite, so it is simply kept. Once read, it can
   be read again on a train, in a village with no signal, or in ten years when
   this domain may no longer answer.

   Strategy:
     navigations  network first, cache as backup  (so a new parva shows up)
     everything else  cache first, refresh behind (so reading is instant)
   The cache name carries a build stamp; a new build drops the old cache. */
const VERSION = 'c1bf4ef23010';
const CACHE = 'mb-' + VERSION;
const ASSETS = [
"./",
"./index.html",
"./assets/style.css",
"./assets/app.js",
"./data/parvas.js",
"./data/content.js",
"./data/characters.js",
"./favicon.svg",
"./manifest.webmanifest",
"./appicons/icon-192.png",
"./appicons/icon-512.png",
"./appicons/icon-maskable-512.png",
"./appicons/apple-touch-icon.png",
"./img/01_nannaya.jpg",
"./img/02_naimisharanya.jpg",
"./img/03_vyasa_ganapati.jpg",
"./img/04_parva_sangraha.jpg",
"./img/05_sarama.jpg",
"./img/06_udanka.jpg",
"./img/07_janamejaya.jpg",
"./img/08_pauloma.jpg",
"./img/09_ruru.jpg",
"./img/10_kadru_vinata.jpg",
"./img/11_garuda.jpg",
"./img/12_parikshit.jpg",
"./img/13_sarpa_yagna.jpg",
"./img/14_uparichara.jpg",
"./img/15_bhubharam.jpg",
"./img/16_kacha.jpg",
"./img/17_devayani.jpg",
"./img/18_yayati.jpg",
"./img/19_puru.jpg",
"./img/20_shakuntala.jpg",
"./img/21_bharata.jpg",
"./img/22_vasus.jpg",
"./img/23_ganga_shantanu.jpg",
"./img/24_bhishma_pratigna.jpg",
"./img/25_amba.jpg",
"./img/26_vyasa_niyoga.jpg",
"./img/27_karna_janana.jpg",
"./img/28_pandu_shapam.jpg",
"./img/29_pandava_janana.jpg",
"./img/30_kaurava_janana.jpg",
"./img/31_drona.jpg",
"./img/32_ekalavya.jpg",
"./img/33_ranga_bhumi.jpg",
"./img/34_drupada.jpg",
"./img/35_yuvaraja.jpg",
"./img/36_lakshagriha.jpg",
"./img/37_escape.jpg",
"./img/38_hidimbi.jpg",
"./img/39_bakasura.jpg",
"./img/40_yajnasena.jpg",
"./img/41_angaraparna.jpg",
"./img/42_tapati.jpg",
"./img/43_nandini.jpg",
"./img/44_parashara.jpg",
"./img/45_swayamvara.jpg",
"./img/46_bhiksha.jpg",
"./img/47_pariksha.jpg",
"./img/48_five_indras.jpg",
"./img/49_vidura.jpg",
"./img/50_indraprastha.jpg",
"./img/51_tilottama.jpg",
"./img/52_varga.jpg",
"./img/53_subhadra.jpg",
"./img/54_harana.jpg",
"./img/55_gandiva.jpg",
"./img/56_khandava.jpg",
"./img/57_sharngaka.jpg",
"./img/58_maya.jpg",
"./img/a_agni_shapa.jpg",
"./img/a_amshavatarana.jpg",
"./img/a_ani_mandavya.jpg",
"./img/a_astika_stops_yaga.jpg",
"./img/a_baka_vadha.jpg",
"./img/a_bhima_duryodhana_janana.jpg",
"./img/a_bhima_poison.jpg",
"./img/a_bird_crocodile.jpg",
"./img/a_chandra_vamsha.jpg",
"./img/a_devavrata_arrows_satyavati.jpg",
"./img/a_dhaumya_shishyulu.jpg",
"./img/a_dhritarashtra_sammati.jpg",
"./img/a_dhritarashtra_vilapa.jpg",
"./img/a_dirghatamas.jpg",
"./img/a_drona_insult.jpg",
"./img/a_drona_school.jpg",
"./img/a_gandhari_vivaham.jpg",
"./img/a_garuda_amritam.jpg",
"./img/a_garuda_elephant_tortoise.jpg",
"./img/a_hastina_return.jpg",
"./img/a_hidimbi_ghatotkacha.jpg",
"./img/a_indrasena.jpg",
"./img/a_jaratkaru_marriage.jpg",
"./img/a_kacha_devayani_shapa.jpg",
"./img/a_kanika_niti.jpg",
"./img/a_karna_anga.jpg",
"./img/a_khanakudu.jpg",
"./img/a_kunti_nishchayam.jpg",
"./img/a_mahabhisha_ganga_vasus.jpg",
"./img/a_pandu_death.jpg",
"./img/a_pandu_kunti_samvadam.jpg",
"./img/a_pandu_vivaham_digvijaya.jpg",
"./img/a_parashara_aurva.jpg",
"./img/a_pratipa_right_thigh.jpg",
"./img/a_sahasrapada.jpg",
"./img/a_samantapanchaka.jpg",
"./img/a_samudra_mathanam.jpg",
"./img/a_sarpa_yagam.jpg",
"./img/a_satyavati_parashara.jpg",
"./img/a_shakuntala_gandharva.jpg",
"./img/a_shakuntala_sabha.jpg",
"./img/a_srishti_vamshalu.jpg",
"./img/a_sutaputra.jpg",
"./img/a_svayamvara_fight.jpg",
"./img/a_svayamvara_sabha.jpg",
"./img/a_takshaka_kashyapa.jpg",
"./img/a_uchchaisravas_wager.jpg",
"./img/a_udanka_nagaloka.jpg",
"./img/a_vidura_hechcharika.jpg",
"./img/a_vidura_mission.jpg",
"./img/a_yayati_devayani_wedding.jpg",
"./img/a_yayati_fall_ashtaka.jpg",
"./img/s01_mayasabha.jpg",
"./img/s02_narada.jpg",
"./img/s03_lokapala.jpg",
"./img/s04_mantra.jpg",
"./img/s05_jara.jpg",
"./img/s06_girivraja.jpg",
"./img/s07_mallayuddha.jpg",
"./img/s08_digvijaya.jpg",
"./img/s09_rajasuya.jpg",
"./img/s10_agrapuja.jpg",
"./img/s11_shishupala_janana.jpg",
"./img/s12_sudarshana.jpg",
"./img/s13_duryodhana_sabha.jpg",
"./img/s14_shakuni.jpg",
"./img/s15_dyutam.jpg",
"./img/s16_draupadi_prashna.jpg",
"./img/s17_vastra.jpg",
"./img/s18_varalu.jpg",
"./img/s19_vanavasa.jpg",
"./img/s_anudyuta.jpg",
"./img/s_dharma_debate.jpg",
"./img/s_digvijaya_south_west.jpg",
"./img/s_draupadi_staked.jpg",
"./img/s_vidura_sent.jpg",
"./icons/abhimanyu.png",
"./icons/adhiratha.png",
"./icons/adrika.png",
"./icons/adrushyanti.png",
"./icons/agni.png",
"./icons/amba.png",
"./icons/ambalika.png",
"./icons/ambika.png",
"./icons/angaraparna.png",
"./icons/anu.png",
"./icons/arjuna.png",
"./icons/aruna.png",
"./icons/aruni.png",
"./icons/aryaka.png",
"./icons/ashtaka.png",
"./icons/ashvasena.png",
"./icons/ashvatthama.png",
"./icons/ashvins.png",
"./icons/astika.png",
"./icons/aurva.png",
"./icons/ayodadhaumya.png",
"./icons/ayu.png",
"./icons/babhruvahana.png",
"./icons/bakasura.png",
"./icons/balarama.png",
"./icons/bali.png",
"./icons/bhagadatta.png",
"./icons/bharadvaja.png",
"./icons/bharata.png",
"./icons/bhima.png",
"./icons/bhishma.png",
"./icons/bhrigu.png",
"./icons/brahma.png",
"./icons/brihadratha.png",
"./icons/brihaspati.png",
"./icons/chandakaushika.png",
"./icons/chitrangada-k.png",
"./icons/chitrangada.png",
"./icons/chyavana.png",
"./icons/dasharaja.png",
"./icons/devala.png",
"./icons/devayani.png",
"./icons/dhaumya.png",
"./icons/dhrishtadyumna.png",
"./icons/dhritarashtra.png",
"./icons/dirghatamas.png",
"./icons/draupadi.png",
"./icons/drona.png",
"./icons/druhyu.png",
"./icons/drupada.png",
"./icons/durvasa.png",
"./icons/duryodhana.png",
"./icons/dushala.png",
"./icons/dushasana.png",
"./icons/dushyanta.png",
"./icons/ekalavya.png",
"./icons/elapatra.png",
"./icons/ganapati.png",
"./icons/gandhari.png",
"./icons/ganga.png",
"./icons/garuda.png",
"./icons/gauramukha.png",
"./icons/ghatotkacha.png",
"./icons/ghritachi.png",
"./icons/ghurnika.png",
"./icons/girika.png",
"./icons/harishchandra.png",
"./icons/hasti.png",
"./icons/hidimba.png",
"./icons/hidimbi.png",
"./icons/indra.png",
"./icons/iravan.png",
"./icons/jaimini.png",
"./icons/jamadagni.png",
"./icons/janamejaya.png",
"./icons/jara.png",
"./icons/jarasandha.png",
"./icons/jaratkaru.png",
"./icons/jitavati.png",
"./icons/kacha.png",
"./icons/kadru.png",
"./icons/kalmashapada.png",
"./icons/kanika.png",
"./icons/kanva.png",
"./icons/karkotaka.png",
"./icons/karna.png",
"./icons/kashyapa.png",
"./icons/kauravas.png",
"./icons/khagama.png",
"./icons/kindama.png",
"./icons/kripa.png",
"./icons/kripi.png",
"./icons/krisha.png",
"./icons/krishna.png",
"./icons/kunti.png",
"./icons/kuntibhoja.png",
"./icons/kuru.png",
"./icons/madri.png",
"./icons/mahabhisha.png",
"./icons/mamata.png",
"./icons/mandapala.png",
"./icons/mandavya.png",
"./icons/matinara.png",
"./icons/maya.png",
"./icons/menaka.png",
"./icons/nahusha.png",
"./icons/nakula.png",
"./icons/nannaya.png",
"./icons/nara.png",
"./icons/narada.png",
"./icons/narayanabhatta.png",
"./icons/paila.png",
"./icons/pandavas.png",
"./icons/pandu.png",
"./icons/parashara.png",
"./icons/parashurama.png",
"./icons/parikshit.png",
"./icons/parjanya.png",
"./icons/parva_01.png",
"./icons/parva_02.png",
"./icons/parva_03.png",
"./icons/parva_04.png",
"./icons/parva_05.png",
"./icons/parva_06.png",
"./icons/parva_07.png",
"./icons/parva_08.png",
"./icons/parva_09.png",
"./icons/parva_10.png",
"./icons/parva_11.png",
"./icons/parva_12.png",
"./icons/parva_13.png",
"./icons/parva_14.png",
"./icons/parva_15.png",
"./icons/parva_16.png",
"./icons/parva_17.png",
"./icons/parva_18.png",
"./icons/paushya.png",
"./icons/prabhasa.png",
"./icons/pradveshini.png",
"./icons/pramadvara.png",
"./icons/pramati.png",
"./icons/pratikami.png",
"./icons/pratipa.png",
"./icons/prishata.png",
"./icons/puloma-r.png",
"./icons/puloma.png",
"./icons/purochana.png",
"./icons/puru.png",
"./icons/pururavas.png",
"./icons/radha.png",
"./icons/rahu.png",
"./icons/rajarajanarendra.png",
"./icons/ruru.png",
"./icons/sahadeva.png",
"./icons/sahasrapada.png",
"./icons/samvarana.png",
"./icons/sanatkumara.png",
"./icons/sanjaya.png",
"./icons/sarama.png",
"./icons/sarameya.png",
"./icons/sarasvati-r.png",
"./icons/satyavati.png",
"./icons/sauti.png",
"./icons/shakti.png",
"./icons/shakuni.png",
"./icons/shakuntala.png",
"./icons/shalva.png",
"./icons/shalya.png",
"./icons/shamika.png",
"./icons/shantanu.png",
"./icons/sharadvan.png",
"./icons/sharmishtha.png",
"./icons/shaunaka.png",
"./icons/shesha.png",
"./icons/shishupala.png",
"./icons/shiva.png",
"./icons/shringi.png",
"./icons/shrutasena.png",
"./icons/shrutashravas.png",
"./icons/shuka.png",
"./icons/shukra.png",
"./icons/shvetaketu.png",
"./icons/somashravas.png",
"./icons/sthulakesha.png",
"./icons/subala.png",
"./icons/subhadra.png",
"./icons/sudeshna-b.png",
"./icons/sukanya.png",
"./icons/sumantu.png",
"./icons/sunanda.png",
"./icons/sunda.png",
"./icons/supratika.png",
"./icons/surya.png",
"./icons/takshaka.png",
"./icons/tapati.png",
"./icons/tilottama.png",
"./icons/turvasu.png",
"./icons/udanka.png",
"./icons/ugrasena-j.png",
"./icons/ulupi.png",
"./icons/upamanyu.png",
"./icons/uparichara.png",
"./icons/upasunda.png",
"./icons/urvashi.png",
"./icons/utathya.png",
"./icons/vaishampayana.png",
"./icons/valakhilyas.png",
"./icons/vapushtama.png",
"./icons/varuna.png",
"./icons/vasishtha.png",
"./icons/vasuki.png",
"./icons/veda.png",
"./icons/vibhavasu.png",
"./icons/vibhishana.png",
"./icons/vichitravirya.png",
"./icons/vidura.png",
"./icons/vikarna.png",
"./icons/vinata.png",
"./icons/vishnu.png",
"./icons/vishvamitra.png",
"./icons/vishvavasu.png",
"./icons/vrishaparva.png",
"./icons/vyasa.png",
"./icons/vyushitashva.png",
"./icons/yadu.png",
"./icons/yaja.png",
"./icons/yama.png",
"./icons/yayati.png",
"./icons/yudhishthira.png",
"./icons/yuyutsu.png"
];

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const c = await caches.open(CACHE);
    // one bad URL must not fail the whole install
    await Promise.all(ASSETS.map(u => c.add(u).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith('mb-') && k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // fonts etc. are the browser's business

  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      try {
        const fresh = await fetch(req);
        (await caches.open(CACHE)).put('./', fresh.clone());
        return fresh;
      } catch (err) {
        return (await caches.match('./')) || (await caches.match('./index.html')) || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const hit = await caches.match(req, { ignoreSearch: true });
    const net = fetch(req).then(res => {
      if (res && res.ok) caches.open(CACHE).then(c => c.put(req, res.clone()));
      return res;
    }).catch(() => null);
    return hit || (await net) || Response.error();
  })());
});
